version: '3'
services:
  api:
    image: 'node:12.19.0'
    working_dir: /api
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=habit
      - PGHOST=db
      - PGPASSWORD=toppass
      - PGDATABASE=habittracker
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./
        target: /api
    command: bash -c "npm install && npm run dev"
  db:
    image: 'postgres:latest'
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=habittracker
      - POSTGRES_USER=habit
      - POSTGRES_PASSWORD=toppass
volumes:
  dbdata: