GET https://wellbeing-habit-tracker-server.herokuapp.com/habits

###

GET http://localhost:5000/habits/1

###

POST http://localhost:3000/habits HTTP/1.1
content-type: application/json

{
    "habit_name": "Meditate",
    "habit_frequency": "Weekly",
    "user_id": "4"
}

###

PUT http://localhost:3000/habits/2 HTTP/1.1
content-type: application/json

{
    "habit_name": "Meditate"
}

###

DELETE http://localhost:3000/habits/1 HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/logs

###

GET http://localhost:3000/logs/habit/3

###

POST http://localhost:3000/logs HTTP/1.1
content-type: application/json

{
    "habit_id": "1",
    "log_date": "2021-10-27",
    "habit_notes": "I did my habit"
}
